config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, path: 'publisher', path_names: { sign_in: '', sign_out: 'logout'}

  ## PUBLISHER
  get '/publisher/inscricoes' => 'publisher/users#index', as: :publisher_users
  get '/publisher/inscricoes/:id/barcode' => 'publisher/users#barcode', as: :barcode_publisher_users
  get '/publisher/inscricoes/busca' => 'publisher/users#search', as: :search_publisher_users
  get '/publisher/inscricoes/filtros' => 'publisher/users#filters', as: :filter_publisher_users
  post   '/publisher/inscricoes/:id/confirm-attended' => 'publisher/users#confirm_attended'
  delete '/publisher/inscricoes/:id' => 'publisher/users#destroy', as: :publisher_user
  
  get '/publisher/noticias' => 'publisher/news#index', as: :news_index
  get '/publisher/noticias/nova' => 'publisher/news#new', as: :new_publisher_news
  post '/publisher/noticias' => 'publisher/news#create', as: :publisher_news
  get '/publisher/noticias/:id/editar' => 'publisher/news#edit', as: :edit_publisher_news
  patch '/publisher/noticias/:id' => 'publisher/news#update', as: :update_publisher_news

  # USERS
  get '/inscricoes' => 'users#new', as: :new_user
  get '/inscricoes/:unique_identifier/confirm-attend' => 'users#confirm_attend'
  post '/users' => 'users#create'

  ## NEWS
  get '/noticias' => 'news#index', as: :news

  post '/visitors/contacts' => 'visitors#contacts', as: :contact_visitors

  get '/,' => 'visitors#index' # fixinig fucking error on mailer 
  root to: 'visitors#index'

  # CERTIFICATE
  get '/certificado(/:name)' => 'visitors#certificate'

  get '/:partial_name' => 'sandbox#index', :partial_name => /.*/
end

app/models/news.rb
# == Schema Information
#
# Table name: news
#
#  id         :integer          not null, primary key
#  title      :string(255)
#  content    :string(255)
#  link       :string(255)
#  created_at :datetime
#  updated_at :datetime
#

class News < ActiveRecord::Base
  validates :title, :link, presence: true

  default_scope { order('created_at DESC') }
end

app/controllers/news_controller.rb
class NewsController < ApplicationController
  def index
    @news = NewsPresenter.map(News.all, view_context)
  end
end

app/controllers/publisher/news_controller.rb
class Publisher::NewsController < Publisher::PublisherController
  defaults resource_class: News
  actions :index, :new, :create, :edit, :update, :destroy

  def permitted_params
    params.permit(news: [:title, :link, :content])
  end

  def create
    create! do |success, _|
      success.html { redirect_to news_index_path, notice: 'Notícia criada com sucesso.' }
    end
  end

  def update
    update! do |success, _|
      success.html { redirect_to news_index_path, notice: 'Notícia editada com sucesso.' }
    end
  end

  protected

  def collection
    @news ||= end_of_association_chain.order('created_at DESC').page params[:page]
  end
end

app/controllers/publisher/publisher_controller.rb
class Publisher::PublisherController < InheritedResources::Base
  layout 'publisher'
  respond_to :html, :json, :csv

  before_action :authenticate_admin!
end

app/controllers/publisher/users_controller.rb
require 'iconv'

class Publisher::UsersController < Publisher::PublisherController
  defaults resource_class: User
  actions :index, :show, :except => [:search, :barcode, :filters]

  def index
    
    @users = User.where(created_at: [Date.today.at_beginning_of_year..Date.today.at_end_of_day]).filter_by_param(params[:query]).page params[:page]

    render action: :index
  end


  def search

    @users = User.where(created_at: [Date.today.at_beginning_of_year..Date.today.at_end_of_day]).filter_by_param(params[:query]).page params[:page]

    render action: :index
  end

  def filters
    @users = UserFiltersManager.new(params).filter

    respond_to do |format|
      format.html do
        @users = @users.page(params[:page] || 1)
        render action: :index
      end

      format.csv do
        content = User.to_csv(@users)
        content = Iconv.conv("iso-8859-1//IGNORE", "utf-8", content) 
        send_data content
      end
    end

  end

  def barcode
    @user = User.find params[:id]

    send_data(@user.barcode_file, filename: "#{@user.unique_identifier}.png", type: 'image/png')
  end

  def destroy
    @user = User.find params[:id]

    @user.destroy

    redirect_to publisher_users_path, notice: 'Usuário removido com sucesso.'
  end

  def confirm_attended
    @user = User.find params[:id]

    if @user.update_attribute(:attended, params[:is_checked])
      head :ok
    else
      head :error
    end
  end

  protected

  def collection
    @users ||= end_of_association_chain.last_created.page params[:page]
  end
end

app/helpers/publisher/publisher_helper.rb
module Publisher::PublisherHelper
  def active?(resource)
    'active' if request.path.match(resource)
  end

  def barcode(user)
    image_tag("barcode/#{user.id}/code128b.png")
  end
end

app/views/publisher/news/_form.html.erb
<%= simple_form_for(@news, url: @news.new_record? ? publisher_news_path : update_publisher_news_path,
      as: 'news', html: { class: 'form-horizontal' },
      wrapper: :horizontal_form,
      wrapper_mappings: {
        check_boxes: :horizontal_radio_and_checkboxes,
        radio_buttons: :horizontal_radio_and_checkboxes,
        file: :horizontal_file_input,
        boolean: :horizontal_boolean
      }) do |f|%>
  <%= f.input :title %>
  <%= f.input :link %>
  <%= f.input :content, as: :text, input_html: { rows: 10 } %>

  <div class='input-wrapper medium'>
    <%= f.button :submit, 'Cadastrar', 'data-disable-with' => '...' %>
  </div>
<% end -%>

app/views/publisher/news/_news.html.erb
<tr>
  <td> <%= news_counter.succ %></td>
  <td> <%= news.title %></td>
  <td> <%= news.link %></td>
  <td> <%= truncate(news.content) %></td>
  <td> <%= link_to "editar", edit_publisher_news_path(news) %></td>
</tr>

app/views/publisher/news/edit.html.erb
<section>
  <h2>
    Editando <i><%= @news.title %></i>
  </h2>

  <%= render 'form' %>
</section>

app/views/publisher/news/index.html.erb
<%= paginate @news %>

<div class="clearfix">
  <%= link_to 'Nova notícia', new_publisher_news_path, class: 'btn btn-primary' %>
</div>

<table class="table table-striped">
  <thead>
    <tr>
      <th>#</th>
      <th>Título</th>
      <th>Link</th>
      <th>Conteúdo</th>
      <th>Ação</th>
    </tr>
  </thead>

  <tbody>
    <%= render partial: 'news', collection: @news %>
  </tbody>
</table>

<%= paginate @news %>

app/views/publisher/news/new.html.erb
<section>
  <h2>Nova notícia</h2>

  <%= render 'form' %>
</section>