config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, path: 'publisher', path_names: { sign_in: '', sign_out: 'logout'}

  ## PUBLISHER
  get '/publisher/inscricoes' => 'publisher/users#index', as: :publisher_users
  get '/publisher/inscricoes/:id/barcode' => 'publisher/users#barcode', as: :barcode_publisher_users
  get '/publisher/inscricoes/busca' => 'publisher/users#search', as: :search_publisher_users
  get '/publisher/inscricoes/filtros' => 'publisher/users#filters', as: :filter_publisher_users
  post   '/publisher/inscricoes/:id/confirm-attended' => 'publisher/users#confirm_attended'
  delete '/publisher/inscricoes/:id' => 'publisher/users#destroy', as: :publisher_user
  
  get '/publisher/noticias' => 'publisher/news#index', as: :news_index
  get '/publisher/noticias/nova' => 'publisher/news#new', as: :new_publisher_news
  post '/publisher/noticias' => 'publisher/news#create', as: :publisher_news
  get '/publisher/noticias/:id/editar' => 'publisher/news#edit', as: :edit_publisher_news
  patch '/publisher/noticias/:id' => 'publisher/news#update', as: :update_publisher_news

  # USERS
  get '/inscricoes' => 'users#new', as: :new_user
  get '/inscricoes/:unique_identifier/confirm-attend' => 'users#confirm_attend'
  post '/users' => 'users#create'

  ## NEWS
  get '/noticias' => 'news#index', as: :news

  post '/visitors/contacts' => 'visitors#contacts', as: :contact_visitors

  get '/,' => 'visitors#index' # fixinig fucking error on mailer 
  root to: 'visitors#index'

  # CERTIFICATE
  get '/certificado(/:name)' => 'visitors#certificate'

  get '/:partial_name' => 'sandbox#index', :partial_name => /.*/
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                :integer          not null, primary key
#  email             :string(255)      default(""), not null
#  created_at        :datetime
#  updated_at        :datetime
#  name              :string(255)
#  company           :string(255)
#  newsletters       :boolean          default(FALSE)
#  phone             :string(255)
#  unique_identifier :string(255)
#

class User < ActiveRecord::Base
  validates :name, :email, :company, presence: true
  validates :email, uniqueness: true
  validates :email, email: true

  scope :filter_by_param, -> (param) {where('users.company ILIKE ? OR users.name ILIKE ? OR users.email ILIKE ?', "%#{param}%", "%#{param}%", "%#{param}%")}

  scope :last_created, -> { order('created_at DESC') }

  before_create :generate_unique_identifier

  def barcode_file
    require 'barby/barcode/code_128'
    require 'barby/outputter/png_outputter'

    Barby::Code128B.new(self.unique_identifier).to_png(height: 50, margin: 5)
  end

  def self.to_csv(users)
    require 'csv'

    CSV.generate(options={}) do |csv|
      csv << ['Name', 'Email', 'Company', 'Pretende Comparecer?' ,'Id']

      users.each do |user|
        csv << [user.name, user.email, user.company, I18n.t(user.want_to_attend.to_s, scope: [:want_to_attend]), user.unique_identifier]
      end
    end
  end

  private

  def generate_unique_identifier
    require 'securerandom'

    self.unique_identifier = SecureRandom.uuid
  end
end

app/controllers/publisher/news_controller.rb
class Publisher::NewsController < Publisher::PublisherController
  defaults resource_class: News
  actions :index, :new, :create, :edit, :update, :destroy

  def permitted_params
    params.permit(news: [:title, :link, :content])
  end

  def create
    create! do |success, _|
      success.html { redirect_to news_index_path, notice: 'Notícia criada com sucesso.' }
    end
  end

  def update
    update! do |success, _|
      success.html { redirect_to news_index_path, notice: 'Notícia editada com sucesso.' }
    end
  end

  protected

  def collection
    @news ||= end_of_association_chain.order('created_at DESC').page params[:page]
  end
end

app/controllers/publisher/publisher_controller.rb
class Publisher::PublisherController < InheritedResources::Base
  layout 'publisher'
  respond_to :html, :json, :csv

  before_action :authenticate_admin!
end

app/controllers/publisher/users_controller.rb
require 'iconv'

class Publisher::UsersController < Publisher::PublisherController
  defaults resource_class: User
  actions :index, :show, :except => [:search, :barcode, :filters]

  def index
    
    @users = User.where(created_at: [Date.today.at_beginning_of_year..Date.today.at_end_of_day]).filter_by_param(params[:query]).page params[:page]

    render action: :index
  end


  def search

    @users = User.where(created_at: [Date.today.at_beginning_of_year..Date.today.at_end_of_day]).filter_by_param(params[:query]).page params[:page]

    render action: :index
  end

  def filters
    @users = UserFiltersManager.new(params).filter

    respond_to do |format|
      format.html do
        @users = @users.page(params[:page] || 1)
        render action: :index
      end

      format.csv do
        content = User.to_csv(@users)
        content = Iconv.conv("iso-8859-1//IGNORE", "utf-8", content) 
        send_data content
      end
    end

  end

  def barcode
    @user = User.find params[:id]

    send_data(@user.barcode_file, filename: "#{@user.unique_identifier}.png", type: 'image/png')
  end

  def destroy
    @user = User.find params[:id]

    @user.destroy

    redirect_to publisher_users_path, notice: 'Usuário removido com sucesso.'
  end

  def confirm_attended
    @user = User.find params[:id]

    if @user.update_attribute(:attended, params[:is_checked])
      head :ok
    else
      head :error
    end
  end

  protected

  def collection
    @users ||= end_of_association_chain.last_created.page params[:page]
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  inherit_resources

  actions :new, :create

  def create
    create! do |success, failure|
      success.html do
        ContactMailer.send_user_confirmation(@user).deliver if Rails.env.production?

        redirect_to new_user_path, notice: 'Inscrição realizada com sucesso.'
      end
    end
  end

  def confirm_attend
    @user = User.find_by_unique_identifier params[:unique_identifier]

    if @user.update_attribute(:want_to_attend, true)
        redirect_to root_path, notice: 'Sua presença no evento foi confirmada com sucesso.'
    else
      flash[:error] = 'Não possível confirmar sua presença no evento devido a um erro no sistema. Tente mais tarde.'
      redirect_to root_path
    end
  end

  private

  def permitted_params
    params.permit(user: [:name, :phone, :rg, :email, :newsletters, :company])
  end
end

app/helpers/publisher/publisher_helper.rb
module Publisher::PublisherHelper
  def active?(resource)
    'active' if request.path.match(resource)
  end

  def barcode(user)
    image_tag("barcode/#{user.id}/code128b.png")
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/publisher/users/_search_box.html.erb
<div class="row">
  <div class="col-md-8">
    <h3><%= t :users, count: @users.total_count %></h3>
  </div>

  <div class='col-md-4'>
    <form class="navbar-form navbar-right" role="search" action="<%= search_publisher_users_path %>" method="get">
      <div class="form-group">
        <input type="text" class="form-control" placeholder="Nome/E-mail/Empresa" name="query" value="<%= params[:query] %>">
      </div>
      <button type="submit" class="btn btn-default">Buscar</button>
    </form>
  </div>
</div>

app/views/publisher/users/_user.html.erb
<tr>
  <td> <%= user.name %></td>
  <td> <%= user.email %></td>
  <td> <%= user.phone.present?? user.phone : '---' %></td>
  <td> <%= user.company %></td>
  <td> <%= t user.newsletters.to_s, scope: [:newsletters, :answer] %></td>
  <td> <%= t user.want_to_attend.to_s, scope: [:want_to_attend] %></td>
  <td> <%= check_box_tag "user[attended]", true, user.attended, data: {id: user.id} %> </td>
  <td> <%= link_to "Remover", publisher_user_path(user), data: {confirm: 'Tem certeza que deseja remover usuário?'}, method: :delete %></td>
</tr>

app/views/publisher/users/index.html.erb
<%= render partial: 'search_box' %>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Nome</th>
      <th>Email</th>
      <th>Telefone</th>
      <th>Empresa/Instituição de Ensino</th>
      <th>Newsletters?</th>
      <th><%= link_to "Prentende Comparecer?", filter_publisher_users_path(by_want_to_attend: true) %></th>
      <th><%= link_to "Compareceu", filter_publisher_users_path(by_attended: true) %></th>
      <th>&nbsp;</th>
    </tr>
  </thead>

  <tbody>
    <%= render partial: 'user', collection: @users %>
  </tbody>
</table>

<%= paginate @users %>