config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, path: 'publisher', path_names: { sign_in: '', sign_out: 'logout'}

  ## PUBLISHER
  get '/publisher/inscricoes' => 'publisher/users#index', as: :publisher_users
  get '/publisher/inscricoes/:id/barcode' => 'publisher/users#barcode', as: :barcode_publisher_users
  get '/publisher/inscricoes/busca' => 'publisher/users#search', as: :search_publisher_users
  get '/publisher/inscricoes/filtros' => 'publisher/users#filters', as: :filter_publisher_users
  post   '/publisher/inscricoes/:id/confirm-attended' => 'publisher/users#confirm_attended'
  delete '/publisher/inscricoes/:id' => 'publisher/users#destroy', as: :publisher_user
  
  get '/publisher/noticias' => 'publisher/news#index', as: :news_index
  get '/publisher/noticias/nova' => 'publisher/news#new', as: :new_publisher_news
  post '/publisher/noticias' => 'publisher/news#create', as: :publisher_news
  get '/publisher/noticias/:id/editar' => 'publisher/news#edit', as: :edit_publisher_news
  patch '/publisher/noticias/:id' => 'publisher/news#update', as: :update_publisher_news

  # USERS
  get '/inscricoes' => 'users#new', as: :new_user
  get '/inscricoes/:unique_identifier/confirm-attend' => 'users#confirm_attend'
  post '/users' => 'users#create'

  ## NEWS
  get '/noticias' => 'news#index', as: :news

  post '/visitors/contacts' => 'visitors#contacts', as: :contact_visitors

  get '/,' => 'visitors#index' # fixinig fucking error on mailer 
  root to: 'visitors#index'

  # CERTIFICATE
  get '/certificado(/:name)' => 'visitors#certificate'

  get '/:partial_name' => 'sandbox#index', :partial_name => /.*/
end

app/controllers/sandbox_controller.rb
class SandboxController < ApplicationController

  def index
    render "/sandbox/#{params[:partial_name] || 'index'}"
  end
end

app/views/sandbox/contato.html.erb
<section id="contact">
  <h2>contato</h2>

  <article>
    <p>Agradecemos seu interesse pelo 2º Fórum Liberdade e Democracia SP. No caso de dúvidas e mais informações, entre em contato conosco através do site.</p>

    <p>Secretaria Executiva</p>

    <p>E-MAIL: <a href="mailto:inscricoes@iflsp.org">inscricoes@iflsp.org</a></p>
  </article>

  <%= form_tag(contact_visitors_path) do%>
    <p class="large">
      <label>Nome Completo</label>
      <input type="text" required="true" name="name">
    </p>

    <p class="large">
      <label>Telefone</label>
      <input type="text" required="true" name="telephone" class="tel">
    </p>
    
    <p class="large">
      <label>E-mail</label>
      <input type="email" required="true" name="email">
    </p>

    <p class="large">
      <label>Mensagem</label>
      <textarea required="true" name="message"></textarea>
    </p>

    <p class="large">
      <%= submit_tag 'Enviar', 'data-disable-with' => '...' %>
    </p>
  <% end -%>

</section>

app/views/sandbox/inscricao.html.erb
<section id="sign-up">
  <h2>inscrição</h2>

  <form action="inscricao_submit" method="get" accept-charset="utf-8">
    <p class="large">
      <label>Nome Completo</label>
      <input type="text" name="name">
    </p>

    <p class="medium">
      <label>CPF</label>
      <input type="text" name="CPF" class='cpf'>
    </p>
    
    <p class="medium">
      <label>RG</label>
      <input type="text" name="RG">
    </p>

    <p class="large">
      <label>E-mail</label>
      <input type="text" name="email">
    </p>

    <p class="large">
      <label>Empresa / Instituição de Ensino</label>
      <input type="text" name="job">
    </p>

    <p class="large">
      <input type="checkbox" id="newsletter" name="newsletter">
      <label for="newsletter" class="chk-newsletter">Desejo receber newsletter</label>
    </p>

    <p class="medium">
      <input type="submit" name="submit" value="Cadastrar">
    </p>
  </form>
</section>

<%= render 'layouts/date_local' %>

app/views/sandbox/palestrantes.html.erb
<article class='award large'>
  <h2>Prêmio Liberdade</h2>
  <figure>
    <%= image_tag('palestrantes/flavio_augusto.png', alt: 'Flavio Augusto receberá o Prêmio Liberdade') %>
  </figure>
  <section class='text'>
      <h3>Flávio Augusto</h3>
      <p>Nascido e criado na periferia do Rio de Janeiro, estudou grande parte do tempo e uma escola pública em seu bairro. Aos 19 anos começou a trabalhar no departamento comercial de uma escola de inglês com a intenção de ter sua própria renda. Depois de algum tempo, trancou a faculdade no curso de Ciências da Computação na Universidade Federal Fluminense e passou a dedicar-se 100% a sua carreira. Foi então que, aos 23 anos de idade, Flávio fundou a WiseUp, usando como capital inicial, R$ 20 mil reais de seu cheque especial a um custo de 12% de juros ao mês. Em 18 anos, a empresa expandiu e tornou-se uma holding avaliada em cerca de R$ 1 bilhão, valor este pago pelo Grupo Abril Educação em fevereiro de 2013, quando adquiriu a holding. Em 2013 Flávio comprou um clube de futebol profissional nos EUA, o Orlando City Soccer Club, na cidade de Orlando. Neste mesmo ano, o Orlando City passou a integrar a MLS - Major League Soccer, elite do futebol norte-americano.</p>
  </section>
</article>
<section id="speakers">
  <h2>Palestrantes</h2>

  <article class="first first-line">
    <h3>Abilio Diniz <i>(Keynote Speaker)</i></h3>

    <figure>
      <%=image_tag('palestrantes/abilio_diniz.jpg', alt: 'Abilio Diniz')%>
    </figure>
    <p>Abilio Diniz é presidente do Conselho de Administração da Península Participações, empresa de investimentos de sua família. Atualmente, Abilio também é presidente do Conselho de Administração da BRF e membro do Conselho de Administração do Carrefour Brasil. Formado em Administração de Empresas pela Fundação Getúlio Vargas foi, ao lado de seu pai, responsável pela criação e desenvolvimento do Grupo Pão de Açúcar, empresa da qual foi presidente do Conselho de Administração até setembro de 2013. Abilio teve também uma participação no governo, entre 1979 e 1989, como membro do Conselho Monetário Nacional. Em 2004, lançou o livro Caminho e Escolhas, e, em 2009, o site <a href="www.abiliodiniz.com.br">www.abiliodiniz.com.br</a>. Desde 2010, ministra o curso Liderança 360º em parceria com a Fundação Getúlio Vargas (FGV), dedicado à formação de jovens líderes.</p>  
  </article>

  <article class="second first-line">
    <h3>David Friedman</h3>
    <figure>
      <%=image_tag('palestrantes/david_friedman.jpg', alt: 'David Friedman')%>
    </figure>
    <p>David Director Friedman nasceu em 1945 em Chicago, Illinois. Filho dos economistas Milton Friedman e Rose Friedman, formou-se em 1965 em Química e Física pela Universidade de Harvard com grandes honras (magna cum laude). Obteve ainda título de Mestre e PhD em física pela Universidade de Chicago (1967 e 1971). Autor do best-seller The Machinery of Freedom e de inúmeros outros artigos, publicações e livros, focou sua carreira na defesa das liberdades, com notável atuação intelectual e acadêmica em teorias político-econômicas. Lecionou em renomadas Universidades como Columbia University, Cornell, UCLA, University of Chicago, e atualmente é professor na School of Law - Santa Clara University.</p>  
  </article>

  <article class="third first-line">
    <h3>Paulo Guedes</h3>
    <figure>
      <%=image_tag('palestrantes/paulo_guedes.jpg', alt: 'Paulo Guedes')%>
    </figure>
    <p>Paulo Guedes é  sócio da Bozano Investimentos, onde atua como chairman of the board. Paulo possui um Phd em economia pela Universidade de Chicago, e tem atuado com relevância no cenário de negócios no Brasil tanto no Mercado de Capitais quanto no Setor Educacional.</p>  
    <p>No mercado de capitais foi um dos quatro fundadores do Banco Pactual que se tornou o maior banco de investimentos privado do Brasil. Foi um dos fundadores da BR Investimentos que deu origem à Bozano Investimentos mediante uma operação de fusão com outras gestoras de recursos.</p>
    <p>No setor educacional foi CEO e sócio controlador do IBMEC, que foi pioneiro na introdução dos MBAs no Brasil, e foi responsável por diversas outras inovações no setor de ensino nas áreas de Business & Law. Atuou como professor de economia no IMPA, PUC-Rio e na FGV, e foi consultor estratégico em diversas companhias no setor de educação. Na BR Investimentos criou uma área dedicada a investimentos no setor educacional e estruturou o fundo BR Educacional, o primeiro fundo de private equity no Brasil dedicado a investimentos nesse setor.</p>
    <p>Paulo Guedes escreve um artigo semanal para o jornal O Globo.</p>

  </article>

  <article class="first second-line">
    <h3>Gustavo Franco</h3>
    <figure>
      <%=image_tag('palestrantes/gustavo_franco.jpg', alt: 'Gustavo Franco')%>
    </figure>
    <p>Gustavo Franco é bacharel e mestre em economia pela PUC do Rio de Janeiro e Ph.D pela Universidade de Harvard. É estrategista-chefe da Rio Bravo e presidente do Instituto Millenium.</p>

    <p>Foi professor, pesquisador e consultor em assuntos de economia, durante 1986-93, especializando-se em inflação, estabilização e economia internacional. Em seguida, no serviço público, durante 1993-99, foi Secretário de Política Econômica (adjunto) do Ministério da Fazenda, Diretor de Assuntos Internacionais e Presidente do Banco Central do Brasil. Teve participação central na formulação, operacionalização e administração do Plano Real, entre outras atividades.
    </p>
    <p>Após ano sabático na universidade (1999), fundou a Rio Bravo Investimentos (2000), empresa de serviços financeiros, fusões, aquisições, investimentos e securitizações, onde atualmente tem a sua ocupação principal. Em paralelo mantém alguma atividade acadêmica (aulas e pesquisas) e escreve para jornais e revistas. </p>
  </article>
  
  <article class="second second-line">
    <h3>Eric Acher</h3>
    <figure>
      <%=image_tag('palestrantes/eric_acher.jpg', alt: 'Eric Acher')%>
    </figure>
    <p>Sócio-fundador da Monashees Capital, gestora de fundos de Venture Capital com foco em start-ups de tecnologia brasileiras, desde 2005Eric vem apoiando empreendedores de alto impacto na criação de mais de 30 empresas inovadoras, entre as quais Oppa, 99Taxis, EduK, Peixe Urbano, Elo7, Mind Lab, Conta Azul, Enjoei e Runrun.it. A Monashees possui parcerias com os principais fundos de Venture Capital do Vale do Silício e é a única gestora da América Latina integrante do Forum Econômico Mundial.</p>  

    <p>Antes de fundar a Monashees, atuou em private equity na General Atlantic e em consultoria estratégica na McKinsey. Pós-graduado em Administração pela Fundação Getúlio Vargas e formado em Comunicação pela ESPM, Eric possui MBA pela Kellogg School of Management.</p>  

    <p>Escritor nas horas vagas, Eric é autor do argumento da graphic novel V.I.S.H.N.U., primeira obra de ficção científica publicada pela Cia. das Letras em 2012.</p>  
  </article>

  <article class="third second-line">
    <h3>Claudio Sassaki</h3>
    <figure>
      <%=image_tag('palestrantes/claudio_sassaki.jpg', alt: 'Claudio Sassaki')%>
    </figure>
    <p>Formado em Arquitetura e Urbanismo pela USP, trabalhou por dois anos em consultoria na área. Possui MBA e Mestrado em Educação por Stanford. Passou cinco anos morando em Nova York trabalhando em ininstituições financeiras. Voltou para o Brasil em 2007, como vice-presidente do banco de investimentos Credit Suisse e depois assumiu o mesmo cargo no Goldman Sachs. Foi também diretor financeiro da Petra Energia. É sócio fundador da Geekie, start-up de aprendizado adaptativo que personaliza o ensino por meio da tecnologia.</p>  
  </article>

  
  <article class="first third-line">
    <h3>Denis Cruz</h3>
    <figure>
      <%=image_tag('palestrantes/denis_cruz.jpg', alt: 'Denis Cruz')%>
    </figure>
    <p>Fundador da Clinica SiM em 2007, Denis Cruz Denis é Administrador de Empresas pela Universidade Federal do Ceará e MBA pela Stanford Graduate School of Business, tendo sido agraciado por esta universidade com um Certificate in Public Management and Social Innovation.</p>
    <p>Após 8 anos trabalhando na área médico-hospitalar, Denis fundou em 2007 a Clínica SiM (Serviço de Inclusão à Medicina), uma rede de clínicas populares próprias e franqueadas que faz mais de 14 mil atendimentos por mês em suas 6 unidades. Baseada em Fortaleza/CE, a Clínica SiM acabou de fechar uma rodada de investimento Series A que a possibilitará atingir 63 unidades em 5 anos, com foco no Norte e Nordeste do Brasil.</p>
  </article>

  <article class="second third-line">
    <h3>Helio Beltrão</h3>
    <figure>
      <%=image_tag('palestrantes/helio_beltrao.jpg', alt: 'Helio Beltrão')%>
    </figure>
    <p>Graduado em finanças com MBA pela Universidade de Columbia, em Nova Iorque. É fundador do Instituto Millenium e presidente do Instituto Mises Brasil. Foi executivo do Banco Garantia e atuou como gestor de fundos e consultor financeiro na Mídia Investimentos e Sextante Investimentos. . Também é membro do conselho de administração do Grupo Ultra e da Metalfrio.</p>
  </article>

</section>

app/views/sandbox/programacao.html.erb
<section id="programming">
  <h2>programação</h2>

  <article>
    <table>
      <tbody>
        <tr>
          <td>14:00</td>
          <td>Credenciamento e Recepção</td>
        </tr>
        <tr>
          <td>15:30</td>
          <td>Cerimônia de Abertura</td>
        </tr>
        <tr>
          <td>15:50</td>
          <td>Keynote Speaker: Abílio Diniz</td>
        </tr>
        <tr>
          <td>16:30</td>
          <td>Painel 1: Liberdade para Empreender</br>
            <i>(David Friedman, Gustavo Franco, Paulo Guedes)</i> 
          </td>
        </tr>
        <tr>
          <td>17:40</td>
          <td>Liberdade em Palavras 1</td>
        </tr>
        <tr>
          <td>17:50</td>
          <td>Liberdade em Palavras 2</td>
        </tr>
        <tr>
          <td>18:00</td>
          <td>Painel 2: Soluções Privadas, Benefícios Públicos</br>
            <i>(Claudio Sassaki, Denis Cruz, Eric Acher)</i></td>
        </tr>
        <tr>
          <td>19:10</td>
          <td>Liberdade em Palavras 3</td>
        </tr>
        <tr>
          <td>19:20</td>
          <td>Liberdade em Palavras 4</td>
        </tr>
        <tr>
          <td>19:30</td>
          <td>Homenagem Prêmio Liberdade: Flávio Augusto</td>
        </tr>
        <tr>
          <td>20:00</td>
          <td>Encerramento do Evento + Acadêmicos de Milton Friedman</br>
            <i>(Nos ajude a trazer a banda Acadêmicos de Milton Friedman <a href="https://partio.com.br/projeto/2-forum-liberdade-e-democracia-2015/" target="_blank">aqui</a>!)</i>
          </td>
        </tr>
      </tbody>
    </table>
  </article>
  
  <%= render 'layouts/date_local' %>
</section>