config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, path: 'publisher', path_names: { sign_in: '', sign_out: 'logout'}

  ## PUBLISHER
  get '/publisher/inscricoes' => 'publisher/users#index', as: :publisher_users
  get '/publisher/inscricoes/:id/barcode' => 'publisher/users#barcode', as: :barcode_publisher_users
  get '/publisher/inscricoes/busca' => 'publisher/users#search', as: :search_publisher_users
  get '/publisher/inscricoes/filtros' => 'publisher/users#filters', as: :filter_publisher_users
  post   '/publisher/inscricoes/:id/confirm-attended' => 'publisher/users#confirm_attended'
  delete '/publisher/inscricoes/:id' => 'publisher/users#destroy', as: :publisher_user
  
  get '/publisher/noticias' => 'publisher/news#index', as: :news_index
  get '/publisher/noticias/nova' => 'publisher/news#new', as: :new_publisher_news
  post '/publisher/noticias' => 'publisher/news#create', as: :publisher_news
  get '/publisher/noticias/:id/editar' => 'publisher/news#edit', as: :edit_publisher_news
  patch '/publisher/noticias/:id' => 'publisher/news#update', as: :update_publisher_news

  # USERS
  get '/inscricoes' => 'users#new', as: :new_user
  get '/inscricoes/:unique_identifier/confirm-attend' => 'users#confirm_attend'
  post '/users' => 'users#create'

  ## NEWS
  get '/noticias' => 'news#index', as: :news

  post '/visitors/contacts' => 'visitors#contacts', as: :contact_visitors

  get '/,' => 'visitors#index' # fixinig fucking error on mailer 
  root to: 'visitors#index'

  # CERTIFICATE
  get '/certificado(/:name)' => 'visitors#certificate'

  get '/:partial_name' => 'sandbox#index', :partial_name => /.*/
end

app/views/layouts/_analytics.html.erb
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-22947130-8', 'auto');
  ga('send', 'pageview');

</script>

app/views/layouts/_date_local.html.erb
<section id="date-local">
  <h2>data / local / hora</h2>

  <p><strong>Dia 19 de Outubro de 2015</strong></p>
  <p>15:30 às 20:00</p>

  <p><strong><a href="https://www.google.com.br/maps/place/Teatro+Renault/@-23.5541468,-46.6383263,16z/data=!4m2!3m1!1s0x94ce59ac3b86967f:0x6f5042e4d9e5086" target="_blank">Teatro Renault</a></strong> <br>
  Av. Brigadeiro Luis Antonio, 411<br>
  Bela Vista/SP</p>

  <p><strong>14h00 Credenciamento e Recepção</strong><br>
   15h30 Cerimônia de Abertura</p>

</section>

app/views/layouts/_footer.html.erb
<footer>
  <section class='companies sponsors'>
    <h5>Apresentadores:</h5>
    <ul>
      <li><%= image_tag('pat-suzano2.jpg') %></li>
      <li><%= image_tag('pat-pottencial.jpg') %></li>
    </ul>
  </section>
  <section class='companies supporters'>
    <h5>Apoiadores:</h5>
    <ul>
      <li><%= image_tag('pat-ceratti.jpg') %></li>
      <li><%= image_tag('pat-evora.jpg') %></li>
      <li><%= image_tag('pat-furdie.jpg') %></li>
      <li><%= image_tag('pat-gerdau.jpg') %></li>
      <li class='extra_large'><%= image_tag('logo_gwc.jpg') %></li>
      <li><%= image_tag('pat-porto-seguros.jpg') %></li>
    </ul>
  </section>
  <section class='companies partners'>
    <h5>Parceiros:</h5>
    <ul>
      <li><%= image_tag('pat-capitalismo-conciente.jpg') %></li>
      <li><%= image_tag('pat-da-insper.jpg') %></li>
      <li class='large'><%= image_tag('pat-estudantes-pelaliberdade.jpg') %></li>
      <li><%= image_tag('pat-iee.jpg') %></li>
      <li><%= image_tag('pat-il.jpg') %></li>
      <li class='large'><%= image_tag('pat-milenium.jpg') %></li>
      <li><%= image_tag('pat-lideres-de-amanha.jpg') %></li>
      <li><%= image_tag('pat-makenzie.jpg') %></li>
      <li><%= image_tag('pat-mises-brasil.jpg') %></li>
      <li><%= image_tag('pat-rede-liberdade.jpg') %></li>
      <li><%= image_tag('pat-srb.jpg') %></li>
    </ul>
  </section>
  <h6>
    <span itemprop="name">2º Fórum Liberdade e Democracia SP </span>
    - Instituto de Formação de Líderes - Dia 19 de Outubro de 2015</h6>
</footer>

app/views/layouts/_header.html.erb
<header>
  <h1>
    <%=link_to image_tag('2_forum_logo.jpg', alt: 'Forum Liberdade e Democracia', class: 'ex', itemprop: "image"), root_path, class: 'bla'%>  
    <div class="button_inscricao">
    <%=link_to 'Inscreva-se'   , 'https://docs.google.com/forms/d/1R0eGJmy4VXpqmSNCwQn0-88yUfxkNeTZ1-dmciECD70/viewform' , target: '_blank' %>
    </div>
  </h1>

  <ul>
    <li><%=link_to 'Programação' , '/programacao', data: {active: current_page?('/programacao')}%></li>
    <li><%=link_to 'Crowdfunding: faça o Fórum com a gente!'   , 'https://partio.com.br/projeto/2-forum-liberdade-e-democracia-2015/' , target: '_blank' %></li>
    <li><%=link_to 'Palestrantes', 'palestrantes', data: {active: current_page?('/palestrantes')}%></li>
    <li><%=link_to 'Notícias'    , news_path     , data: {active: current_page?('/noticias')} %></li>
    <li><%=link_to 'Inscrição'   , 'https://docs.google.com/forms/d/1R0eGJmy4VXpqmSNCwQn0-88yUfxkNeTZ1-dmciECD70/viewform' , target: '_blank' %></li>
    <li><%=link_to 'Contato'     , '/contato'    , data: {active: current_page?('/contato')}%></li>
  </ul>

  <section class="social">
    <p>nos acompanhe:</p>
    <%=link_to image_tag('icon-facebook.jpg', alt: 'Facebook'), 'https://www.facebook.com/pages/F%C3%B3rum-Liberdade-e-Democracia-SP/1511251855756392?fref=ts', target: 'blank' %>
  </section>
    <%=link_to image_tag('logo-ifl.jpg', alt: 'Instituto de Formação de Líderes', class: 'logo-ifl'), "http://www.iflsp.org", target: 'blank' %>
    
  <section class="local-date">
    <b itemprop="startDate" content="2015-10-19">19 de Outubro de 2015</b>
    <p>15:30 às 20:00</p>
    <p itemprop="location" itemscope itemtype="http://schema.org/Place">
      <span itemprop="name">Teatro Renault </span> - 
      <span itemprop="address" itemscope itemtype="http://schema.org/PostalAddress">
        <span itemprop="streetAddress">Av. Brigadeiro Luis Antonio, 411 </span> - 
        <span itemprop="addressLocality">Bela Vista / SP</span>
      </span>
    </p>
  </section>

</header>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Forum Liberdade Democracia" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Forum Liberdade Democracia" %>">
    <link href='http://fonts.googleapis.com/css?family=Open+Sans:400,300,700,600,800' rel='stylesheet' type='text/css'>
    <link rel="icon" type="image/ico" href="<%= image_url('favicon.ico') %>">
    <%= stylesheet_link_tag 'application', media: 'all'%>
    <%= csrf_meta_tags %>


    <!-- Facebook Pixel Code -->
    <script>
    !function(f,b,e,v,n,t,s){if(f.fbq)return;n=f.fbq=function(){n.callMethod?
    n.callMethod.apply(n,arguments):n.queue.push(arguments)};if(!f._fbq)f._fbq=n;
    n.push=n;n.loaded=!0;n.version='2.0';n.queue=[];t=b.createElement(e);t.async=!0;
    t.src=v;s=b.getElementsByTagName(e)[0];s.parentNode.insertBefore(t,s)}(window,
    document,'script','//connect.facebook.net/en_US/fbevents.js');

    fbq('init', '1664024053854257');
    fbq('track', "PageView");</script>
    <noscript><img height="1" width="1" style="display:none"
    src="https://www.facebook.com/tr?id=1664024053854257&ev=PageView&noscript=1"
    /></noscript>
    <!-- End Facebook Pixel Code -->

    <!-- Código do Google para tag de remarketing -->
    <script type="text/javascript">
    /* <![CDATA[ */
    var google_conversion_id = 939524767;
    var google_custom_params = window.google_tag_params;
    var google_remarketing_only = true;
    /* ]]> */
    </script>
    <script type="text/javascript" src="//www.googleadservices.com/pagead/conversion.js">
    </script>
    <noscript>
    <div style="display:inline;">
    <img height="1" width="1" style="border-style:none;" alt="" src="//googleads.g.doubleclick.net/pagead/viewthroughconversion/939524767/?value=0&amp;guid=ON&amp;script=0"/>
    </div>
    </noscript>

  </head>
  <body itemscope itemtype="http://schema.org/Event">
    <%= render 'layouts/messages' %>
    <%= render 'layouts/header' %>

    <%= yield %>

    <%= render 'layouts/footer' %>
    <%= render 'layouts/analytics' if Rails.env.production? %>

    <%= javascript_include_tag 'application' %>
    <%= javascript_include_tag '/grid.js' if Rails.env.development? %>
  </body>
</html>

app/views/layouts/certificate.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Forum Liberdade Democracia" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Forum Liberdade Democracia" %>">
    <link href='http://fonts.googleapis.com/css?family=Open+Sans:400,300,700,600,800' rel='stylesheet' type='text/css'>
    <%= stylesheet_link_tag 'application', media: 'all'%>
    <%= csrf_meta_tags %>
  </head>
  <body itemscope itemtype="http://schema.org/Event">
    <%= yield %>

    <%= javascript_include_tag 'application' %>
  </body>
</html>

app/views/layouts/publisher.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Forum Liberdade Democracia" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Forum Liberdade Democracia" %>">
    <link href='http://fonts.googleapis.com/css?family=Open+Sans:400,300,700,600,800' rel='stylesheet' type='text/css'>
    <%= stylesheet_link_tag 'publisher/publisher', media: 'all' %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <%= render 'layouts/messages' %>

    <div class="navbar navbar-inverse" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>

          <%= link_to "Fórum Liberdade e Democracia", publisher_users_path, class: 'navbar-brand' %>
        </div>
        <% if admin_signed_in? %>
          <div class="collapse navbar-collapse">
            <ul class="nav navbar-nav">
              <li class='<%= active?('inscricoes') %>'>
                <%= link_to "Inscrições", publisher_users_path %>
              </li>

              <li class='<%= active?('noticias') %>'>
                <%= link_to "Notícias", news_index_path %>
              </li>
              <li>
                <%= link_to "Logout", destroy_admin_session_path, method: :delete %>
              </li>
            </ul>
          </div><!--/.nav-collapse-->
        <% end %>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <%= yield %>
      </div>
    </div><!--/.container-->

    <%= javascript_include_tag 'publisher/publisher.js' %>
    <%= javascript_include_tag '/grid.js' if Rails.env.development? %>
  </body>
</html>